---
- name: add apt key
  become: yes
  apt_key:
    url: https://deb.nodesource.com/gpgkey/nodesource.gpg.key

- name: add apt repo
  become: yes
  apt_repository:
    repo: deb https://deb.nodesource.com/node_6.x jessie main

- name: add apt sources repo
  become: yes
  apt_repository:
    repo: deb-src https://deb.nodesource.com/node_6.x jessie main

- name: install
  become: yes
  apt:
    name: nodejs
    state: latest
    update_cache: yes
