---
- name: add apt repository
  become: true
  apt_repository:
    repo: deb http://dl.google.com/linux/chrome/deb/ stable main

- name: add apt key
  become: true
  apt_key:
    url: https://dl.google.com/linux/linux_signing_key.pub

- name: install
  become: true
  apt:
    name: google-chrome-stable
    state: latest
    update_cache: true