---
- name: get erlang solutions repo package
  get_url:
    url: https://packages.erlang-solutions.com/erlang-solutions_1.0_all.deb
    dest: /tmp

- name: install repo package
  become: yes
  apt:
    deb: /tmp/erlang-solutions_1.0_all.deb

- name: install erlang
  become: yes
  apt:
    name: esl-erlang
    update_cache: yes

- name: install elixir
  become: yes
  apt:
    name: elixir
    update_cache: yes
