---
- hosts: localhost
  pre_tasks:
    - name: install basics
      become: yes
      apt: name={{ item }}
      with_items:
        - curl
        - vim
  roles:
    - git
    - chrome
    - sublime
    - docker
    - autojump
    - clojure
    - elixir
    - nodejs
