---
- hosts: localhost
  pre_tasks:
    - name: install basics
      become: yes
      apt: name={{ item }}
      with_items:
        - atool
        - curl
        - fonts-firacode
        - jq
        - python-pip
        - vim
  roles:
    - dotfiles
    - git
    - chrome
    - docker
    - autojump
    - clojure
    - elixir
    - nodejs
